/*
** EPITECH PROJECT, 2026
** Cartridge
** File description:
** starwars
*/

#include "sound_note.h"

const uint8_t starwars_music[] =
{
    PE,RT,D4,PE,RT,D4,PE,RT,D4,PH,RE,G4,PH,RQ,D5,PE,RT,C5,PE,RT,B4,PE,RT,A4,PH,RE,G5,PE,RQ,D5,
    PE,RT,C5,PE,RT,B4,PE,RT,A4,PH,RE,G5,PE,RQ,D5,PE,RT,C5,PE,RT,B4,PE,RT,C5,PH,RH,A4,PE,RT,D4,PE,RE,D4,PH,RE,G4,PH,RE,D5,
    PE,RT,C5,PE,RT,B4,PE,RT,A4,PH,RE,G5,PE,RQ,D5,PE,RT,C5,PE,RT,B4,PE,RT,A4,PH,RE,G5,PE,RQ,D5,PE,RT,C5,PE,RT,B4,PE,RT,C5,PH,RH,A4,PE,RT,D4,PE,RE,D4,
    PE,RT,E4,PQ,RQ,E4,PQ,RS,C5,PQ,RS,B4,PE,RS,A4,PE,RS,G4,PE,RT,G4,PE,RT,A4,PE,RT,B4,PE,RS,A4,PQ,RE,E4,PE,RT,Fs4,
    END,END,END
};
